--- # prj-atq .. task 2 -- modify /etc/hosts and the setup & configure ntp info.
- hosts: project-task2
  connection: ssh
  remote_user: root
#  become: yes
  gather_facts: yes
  vars_files:
    - init_vars.yml
  tasks:
    - name: install/verify ntpd is installed. # install NTP if need be.
      yum:
        name: ntp
        state: installed
    - name: ensure firewall allows ntp. # open firewalld for ntp
      firewalld:
        immediate: yes
        permanent: yes
        service: ntp
        state: enabled
      ignore_errors: yes # allows this to continue if firewalld isn't there.
    - name: enable ntpd at boot
      service: name=ntpd enabled=yes state=started
    - name: set ntp on host1
      template:
        src: templates/ntp1.j2
        dest: /etc/ntp.conf
        backup: yes
      when:
        ansible_fqdn == "host1.adj.home"
    - name: set ntp on host2
      template:
        src: templates/ntp2.j2
        dest: /etc/ntp.conf
        backup: yes
      when:
        ansible_fqdn == "host2.adj.home"
    - name: set ntp on host3
      template:
        src: templates/ntp3.j2
        dest: /etc/ntp.conf
        backup: yes
      when: 
        ansible_fqdn == "host3.adj.home"
# reload ntpd on the 3 CTs, so the config is taken.
    - name: reload ntpd config.
      service: name=ntpd state=reloaded
