--- # prj-atq .. task 2 -- modify /etc/hosts and the setup & configure ntp info.
- hosts: project-task2
  connection: ssh
  user: scotty
  become: yes
  gather_facts: yes
  vars_files:
    - init_vars.yml
  tasks:
    - name: install/verify ntpd is installed. # install NTP if need be.
      yum:
        name: ntpd
        state: installed
    - name: ensure firewall allows ntp. # open firewalld for ntp
      firewalld:
        immediate: yes
        permanent: yes
        service: ntp
        state: enabled
      ignore_errors: yes # allows this to continue if firewalld isn't there.
    - name: enable ntpd at boot
      service: name=ntpd enabled=yes state=started
    - name: set ntp on host1
      template:
        src: templates/ntp1.j2
        dest: /etc/ntp.conf
        backup: yes
      when:
        ansible_hostname == "{{ ct1-fqdn }}"
    - name: set ntp on host 2 and host 3 (the same)
      template:
        src: templates/ntp2-3.j2
        dest: /etc/ntp.conf
        backup: yes
      when:
        (ansible_hostname == "{{ ct2-fqdn }}") or
        (ansible_hostname == "{{ ct3-fqdn }}")
# reload ntpd on the 3 CTs, so the config is taken.
    - name: reload ntpd config.
      service: name=ntpd state=reloaded
