--- # prj-atq .. task 2 -- modify /etc/hosts
- hosts: project-task2
  connection: ssh
  remote_user: root
#  become: yes
  gather_facts: yes
  vars_files:
    - init_vars.yml
  tasks:
    - name: template the etc/hosts for host1
      template:
        src: templates/etchost1.j2
        dest: /etc/hosts
        backup: yes
      when:
        ansible_fqdn == "host1.adj.home"
    - name: template the etc/hosts for host2
      template:
        src: templates/etchost2.j2
        dest: /etc/hosts
        backup: yes
      when:
        ansible_fqdn == "host2.adj.home"
    - name: template the etc/hosts for host3
      template:
        src: templates/etchost3.j2
        dest: /etc/hosts
        backup: yes
      when:
        ansible_fqdn == "host3.adj.home"
