--- # full playbook to create 3 CTs.
- hosts: prox # contains only the hypervisor proxmox and the ansible master.
  user: scotty
  gather_facts: smart
  connection: ssh
#  vars_files:
#    - init_vars.yml # contains the variables for building the CTs.
  tasks:
    - include: plays/prox-build-ct1.yml
    - include: plays/prox-build-ct2.yml
    - include: plays/prox-build-ct3.yml
   #   wait
    - include: plays/start3-cts.yml
