--- # 3 CTs get apache running.
- hosts: project-task2 # all 3 CTs
  connection: ssh
  gather_facts: yes
  #user: scotty # this is the operative ansible user
 # become: yes
  remote_user: root
  vars_files:
    - init_vars.yml # contains the variables for building the CTs.
  tasks:
    - name: install apache on CTs.
      yum:
          update_cache: yes
          name: httpd
          state: present
    - name: make apache run run run
      service:
          name: httpd
          enabled: yes
          state: started
    - name: create html dir
      file:
          path: /var/www/html
          state: directory
          mode: 0755
          owner: apache
          group: apache
    - name: put html file from template and post it to all 3 servers.
      template:
          src: templates/htmlpage.j2
          dest: /var/www/html/index.html
          backup: yes
          force: yes
    - name: setup apache config via template
      template:
          src: templates/httpdconf.j2
          dest: /etc/httpd/conf.d/atq.conf
